### ISSUE TITLE
Send function isn't returning an Error when it should

### ISSUE THREAD

**Issue by justinclift** [smtp2go-oss/smtp2go-go#3]
Been trying to figure out why the `Send()` function call isn't working as expected:

```
email := smtp2go.Email{
	From:     "Newdash.io <reply@newdash.io>",
	To:       []string{fmt.Sprintf("<%s>", emailAddr)},
	Subject:  "Please verify your email address",
	TextBody: fmt.Sprintf("Please visit this url to confirm your email address: %v", verifyURL),
	HtmlBody: fmt.Sprintf(`Please visit this url to verify your email address: <a href="%v">%v</a>`, verifyURL, verifyURL),
}

_, err := smtp2go.Send(&email)
if err != nil {
	log.Println(err)
	return
}
log.Printf("Verification email sent to '%v'", emailAddr)
```

That's all pretty standard Go code, and the function is returning without generating any kind of error. (!)

Except email isn't being delivered, and the SMTP2Go website isn't showing it's receiving anything.

Thus spending a few hours trying to figure out WTF is going on.

It turns out the `Send()` function call in this library is really weird, actually returning errors in the function body.

Changing the above code to match the example then blindly display the object shows the real problem:

```
res, err := smtp2go.Send(&email)
// ...
log.Printf("Sent Successfully: %s", res)
```

The output now says:

```
2024/04/12 16:02:32 Sent Successfully: &{3daa20c2-f892-11ee-b1a6-f23c9216bfec {An error occurred processing
the json data you sent with the request. Please make sure the data conforms to the specification for this
call (see the documentation here: https://developers.smtp2go.com/reference/introduction-1) and try again.
Don't forget to set Content-Type to 'application/json'. E_ApiResponseCodes.NON_VALIDATING_IN_PAYLOAD
{sender The field 'sender' was expecting a valid RFC-822 formatted email field but found 'Newdash.io
<reply@newdash.io>', Please correct your JSON payload and try again.}}}
```

So, it's really a malformed email address being the problem with my code.

No worries, that's fixable.

But what the heck is up with the `Send()` function wrongly indicating success rather than using the error code it literally returns? :wink:

Please fix this, it's a pretty bad bug.

**Comment by matthewljsmith** [comment]
@justinclift hmm yeah that is an oversight for certain, I've made it return an error in the event the api responds with an error, please update to v1.0.3 and this will be resolved for you. Thank you for pointing it out ;)

**Comment by justinclift** [comment]
Cool, thanks.  I should have time to verify this is working in the next few days. :smile:

**Comment by justinclift** [comment]
Forgot to follow up with this issue.  Yep, this worked when I got around to testing it (ages ago). :smile:
